#**Pre-Trained BERT Model**






We can download this model from Keras Hub. We will work with a subsequently released version of BERT, RoBERTA, which is robustly optimized (Ro). The model's main value was that it was trained on 10x the amount of data though, so it's better tuned.

In [1]:
import keras_hub

# Backbone here refers to the RoBERTa base layers
tokenizer = keras_hub.models.Tokenizer.from_preset("roberta_base_en")
backbone = keras_hub.models.Backbone.from_preset("roberta_base_en")

100%|██████████| 445/445 [00:00<00:00, 1.36MB/s]


100%|██████████| 686/686 [00:00<00:00, 1.24MB/s]


100%|██████████| 0.99M/0.99M [00:01<00:00, 752kB/s]


100%|██████████| 446k/446k [00:01<00:00, 371kB/s]


100%|██████████| 474M/474M [00:34<00:00, 14.4MB/s]


We need to use the tokenizer that goes with the model to make sure it pre-processes our text in a way that the model expects.

In [2]:
tokenizer("The quick brown fox")

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([  133,  2119,  6219, 23602], dtype=int32)>

Here are the base layers we loaded. Notice that it is essentially a token embedding layer with some normalization afterward, some dropout to the embeddings to avoid overfitting, and then a ton of stacked transformer encoders.

In [3]:
backbone.summary()

Model: "roberta_backbone"

┏━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┓
┃ Layer (type)        ┃ Output Shape      ┃    Param # ┃ Connected to      ┃
┡━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━┩
│ token_ids           │ (None, None)      │          0 │ -                 │
│ (InputLayer)        │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ embeddings          │ (None, None, 768) │ 38,996,736 │ token_ids[0][0]   │
│ (TokenAndPositionE… │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ embeddings_layer_n… │ (None, None, 768) │      1,536 │ embeddings[0][0]  │
│ (LayerNormalizatio… │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ embeddings_dropout  │ (None, None, 768) │          0 │ embeddings_layer… │
│ (Dropout)           │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ padding_mask        │ (None, None)      │          0 │ -                 │
│ (InputLayer)        │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ transformer_layer_0 │ (None, None, 768) │  7,087,872 │ embeddings_dropo… │
│ (TransformerEncode… │                   │            │ padding_mask[0][… │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ transformer_layer_1 │ (None, None, 768) │  7,087,872 │ transformer_laye… │
│ (TransformerEncode… │                   │            │ padding_mask[0][… │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ transformer_layer_2 │ (None, None, 768) │  7,087,872 │ transformer_laye… │
│ (TransformerEncode… │                   │            │ padding_mask[0][… │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ transformer_layer_3 │ (None, None, 768) │  7,087,872 │ transformer_laye… │
│ (TransformerEncode… │                   │            │ padding_mask[0][… │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ transformer_layer_4 │ (None, None, 768) │  7,087,872 │ transformer_laye… │
│ (TransformerEncode… │                   │            │ padding_mask[0][… │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ transformer_layer_5 │ (None, None, 768) │  7,087,872 │ transformer_laye… │
│ (TransformerEncode… │                   │            │ padding_mask[0][… │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ transformer_layer_6 │ (None, None, 768) │  7,087,872 │ transformer_laye… │
│ (TransformerEncode… │                   │            │ padding_mask[0][… │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ transformer_layer_7 │ (None, None, 768) │  7,087,872 │ transformer_laye… │
│ (TransformerEncode… │                   │            │ padding_mask[0][… │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ transformer_layer_8 │ (None, None, 768) │  7,087,872 │ transformer_laye… │
│ (TransformerEncode… │                   │            │ padding_mask[0][… │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ transformer_layer_9 │ (None, None, 768) │  7,087,872 │ transformer_laye… │
│ (TransformerEncode… │                   │            │ padding_mask[0][… │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ transformer_layer_… │ (None, None, 768) │  7,087,872 │ transformer_laye… │
│ (TransformerEncode… │                   │            │ padding_mask[0][… │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ transformer_layer_… │ (None, None, 768) │  7,087,872 │ transformer_laye

 Total params: 124,052,736 (473.22 MB)

 Trainable params: 124,052,736 (473.22 MB)

 Non-trainable params: 0 (0.00 B)

Let's try using this pre-trained model with our IMDB reviews...

In [4]:
import os, pathlib, shutil, random, keras

zip_path = keras.utils.get_file(
    origin="https://ai.stanford.edu/~amaas/data/sentiment/aclImdb_v1.tar.gz",
    fname="imdb",
    extract=True,
)

imdb_extract_dir = pathlib.Path(zip_path) / "aclImdb"
train_dir = pathlib.Path("imdb_train")
test_dir = pathlib.Path("imdb_test")
val_dir = pathlib.Path("imdb_val")

shutil.copytree(imdb_extract_dir / "test", test_dir, dirs_exist_ok=True)

val_percentage = 0.2
for category in ("neg", "pos"):
    src_dir = imdb_extract_dir / "train" / category
    src_files = os.listdir(src_dir)
    random.Random(1337).shuffle(src_files)
    num_val_samples = int(len(src_files) * val_percentage)

    os.makedirs(train_dir / category, exist_ok=True)
    os.makedirs(val_dir / category, exist_ok=True)
    for index, file in enumerate(src_files):
        if index < num_val_samples:
            shutil.copy(src_dir / file, val_dir / category / file)
        else:
            shutil.copy(src_dir / file, train_dir / category / file)

84125825/84125825 ━━━━━━━━━━━━━━━━━━━━ 12s 0us/step


Create our Tensorflow Dataset objects from the .txt files now

In [5]:
batch_size = 16
train_ds = keras.utils.text_dataset_from_directory(
    train_dir, batch_size=batch_size
)
val_ds = keras.utils.text_dataset_from_directory(
    val_dir, batch_size=batch_size
)
test_ds = keras.utils.text_dataset_from_directory(
    test_dir, batch_size=batch_size
)

Found 20000 files belonging to 2 classes.
Found 5000 files belonging to 2 classes.
Found 25000 files belonging to 2 classes.


We apply the RoBERTa tokenizer to our datasets now. Before we go to the RoBERTa tokenizer, however, we need to add some start and end tokens, and some padding tokens, that were present in the dataset that was used for training RoBERTa.

In [6]:
# We are 'packing' on some additional tokens here. Sequences up to 512 tokens, adding the start token to our reviews, the end token, and the padding token for reviews shorter than 512 words.
def preprocess(text, label):
    packer = keras_hub.layers.StartEndPacker(
        sequence_length=512,
        start_value=tokenizer.start_token_id,
        end_value=tokenizer.end_token_id,
        pad_value=tokenizer.pad_token_id,
        return_padding_mask=True,
    )

    # After adding those tokens, we can apply RoBERTa's tokenizer
    token_ids, padding_mask = packer(tokenizer(text))
    return {"token_ids": token_ids, "padding_mask": padding_mask}, label

# And now that our preprocessing function is written, we can apply it to our Tensorflow Datasets
preprocessed_train_ds = train_ds.map(preprocess)
preprocessed_val_ds = val_ds.map(preprocess)
preprocessed_test_ds = test_ds.map(preprocess)

Here is a pre-processed batch of data. We have integer sequences per review, and a masking vector for each one that tells RoBERTa which tokens it can ignore at inference.

In [7]:
next(iter(preprocessed_train_ds))

({'token_ids': <tf.Tensor: shape=(16, 512), dtype=int32, numpy=
  array([[    0,   133, 18754, ...,     1,     1,     1],
         [    0, 13863,  7883, ...,     1,     1,     1],
         [    0,   100,   657, ...,     1,     1,     1],
         ...,
         [    0,   243,    18, ...,     1,     1,     1],
         [    0,   713, 11110, ...,     1,     1,     1],
         [    0, 21518,    65, ...,     1,     1,     1]], dtype=int32)>,
  'padding_mask': <tf.Tensor: shape=(16, 512), dtype=bool, numpy=
  array([[ True,  True,  True, ..., False, False, False],
         [ True,  True,  True, ..., False, False, False],
         [ True,  True,  True, ..., False, False, False],
         ...,
         [ True,  True,  True, ..., False, False, False],
         [ True,  True,  True, ..., False, False, False],
         [ True,  True,  True, ..., False, False, False]])>},
 <tf.Tensor: shape=(16,), dtype=int32, numpy=array([0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1], dtype=int32)>)

Okay, now we can add some Dense layers onto the RoBERTa backbone and use it for our predictions!

In [8]:
from keras import layers

inputs = backbone.input
x = backbone(inputs)

# Freeze the backbone layers
backbone.trainable = False

# This is isolating a specific embedding from RoBERTa's backbone output that is akin to the document embedding.
# This embedding is associated with the CLS (classification) token.
# The CLS token is a specific token (a fixed value) that is added at the beginning of every textual sequence in RoBERTa's training data.
# The Neural Net learns to shift this token's embedding around depending on all the words that appear in a given sentence, to inform Next Sentence Prediction (NSP).
# As the model achieves its self-supervised NSP goal, it learns how to produce a CLS token embedding for a a pair of sentences of text.
# Note that this is generally more useful / less noisy than doing something like averaging all the word-level BERT embeddings from the sentence.
x = x[:, 0, :]

x = layers.Dropout(0.1)(x)

# Each CLS embedding is a 768 dimensional vector; we are allowing some transformation of the embedding with a relu activation, then doing dropout and going to a sigmoid prediction.
x = layers.Dense(768, activation="relu")(x)
x = layers.Dropout(0.1)(x)
outputs = layers.Dense(1, activation="sigmoid")(x)

classifier = keras.Model(inputs, outputs)

classifier.compile(
    optimizer=keras.optimizers.Adam(5e-5),
    loss="binary_crossentropy",
    metrics=["accuracy"],
)

classifier.fit(
    preprocessed_train_ds,
    validation_data=preprocessed_val_ds,
    epochs=5
)

Epoch 1/5
1250/1250 ━━━━━━━━━━━━━━━━━━━━ 113s 64ms/step - accuracy: 0.6773 - loss: 0.6438 - val_accuracy: 0.8410 - val_loss: 0.5788
Epoch 2/5
1250/1250 ━━━━━━━━━━━━━━━━━━━━ 66s 51ms/step - accuracy: 0.7962 - loss: 0.5492 - val_accuracy: 0.8478 - val_loss: 0.4927
Epoch 3/5
1250/1250 ━━━━━━━━━━━━━━━━━━━━ 66s 51ms/step - accuracy: 0.8126 - loss: 0.4889 - val_accuracy: 0.8592 - val_loss: 0.4328
Epoch 4/5
1250/1250 ━━━━━━━━━━━━━━━━━━━━ 66s 51ms/step - accuracy: 0.8264 - loss: 0.4529 - val_accuracy: 0.8636 - val_loss: 0.3940
Epoch 5/5
1250/1250 ━━━━━━━━━━━━━━━━━━━━ 66s 51ms/step - accuracy: 0.8348 - loss: 0.4244 - val_accuracy: 0.8710 - val_loss: 0.3666
